apiVersion: v1
kind: ConfigMap
metadata:
  name: redteam-config
data:
  config.json: |
    {
      "name": "Kubernetes Red Team Evaluation",
      "models": [
        {
          "provider": "openai",
          "model_id": "gpt-4",
          "parameters": {
            "temperature": 0.7,
            "max_tokens": 1000
          },
          "api_key_env": "OPENAI_API_KEY"
        },
        {
          "provider": "anthropic",
          "model_id": "claude-3-opus",
          "parameters": {
            "temperature": 0.7,
            "max_tokens": 1000
          },
          "api_key_env": "ANTHROPIC_API_KEY"
        }
      ],
      "dataset": "/data/attack_vectors.json",
      "parameters": {
        "sample_size": 50,
        "confidence_level": 0.95,
        "success_threshold": 0.8,
        "seed": 42,
        "parallelism": 4
      },
      "evaluation": {
        "method": "rule-based"
      },
      "output": {
        "path": "/data/results",
        "format": "json",
        "include_responses": true,
        "save_results": true
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  # These are placeholder base64 values - replace with your actual API keys
  OPENAI_API_KEY: b3BlbmFpLWtleQ==  # Replace with echo -n "your-key" | base64
  ANTHROPIC_API_KEY: YW50aHJvcGljLWtleQ==  # Replace with echo -n "your-key" | base64
  GOOGLE_API_KEY: Z29vZ2xlLWtleQ==  # Replace with echo -n "your-key" | base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redteamer-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redteamer-job
  labels:
    app: redteamer
spec:
  backoffLimit: 3
  parallelism: 1
  completions: 1
  ttlSecondsAfterFinished: 3600  # Auto-delete job after 1 hour
  template:
    metadata:
      labels:
        app: redteamer
    spec:
      containers:
      - name: redteamer
        image: redteamer:latest  # Replace with your image
        command: ["redteamer", "run", "--config", "/etc/redteamer/config.json", "--non-interactive", "--verbose"]
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/redteamer
        - name: data-volume
          mountPath: /data
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: ANTHROPIC_API_KEY
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: GOOGLE_API_KEY
      volumes:
      - name: config-volume
        configMap:
          name: redteam-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: redteamer-data-pvc
      restartPolicy: Never 